// starters/vue/src/App.vue
<script setup lang="ts">
import { useQuery, gql } from '@quenetiq/vue';

interface Note {
  id: string;
  title: string;
  content: string;
}

const GET_NOTES = gql`
  query {
    getNotes {
      id
      title
      content
    }
  }
`;

const { data, loading, error } = useQuery<{ getNotes: Note[] }>(GET_NOTES);
</script>

<template>
  <h1>DumbQL + Vue</h1>
  <p v-if="loading">Loading...</p>
  <p v-else-if="error">{{ error }}</p>
  <ul v-else>
    <li v-for="note in data?.getNotes" :key="note.id">
      <strong>{{ note.title }}</strong>: {{ note.content }}
    </li>
  </ul>
</template>

<style>
body { font-family: sans-serif; padding: 2rem; }
</style>

// demos/react/src/App.tsx
import { gql, useQuery } from '@quenetiq/react';

const GET_NOTES = gql`
  query {
    getNotes {
      id
      title
      content
    }
  }
`;

export function App() {
  const { data, loading, error } = useQuery(GET_NOTES);

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error: {error}</p>;

  return (
    <div>
      <h1>Quenetiq + React</h1>
      <ul>
        {data?.getNotes?.map((note: { id: string; title: string; content: string }) => (
          <li key={note.id}><strong>{note.title}</strong>: {note.content}</li>
        ))}
      </ul>
    </div>
  );
}
