// projects/quenetiq/react/src/lib/skeleton.tsx
import { type CSSProperties, type ReactNode } from 'react';

export type SkeletonVariant = 'text' | 'circle' | 'rect' | 'card' | 'table' | 'list' | 'paragraph';
export type SkeletonAnimation = 'pulse' | 'wave' | 'none';

export interface SkeletonProps {
	readonly variant?: SkeletonVariant;
	readonly animation?: SkeletonAnimation;
	readonly width?: string | number;
	readonly height?: string | number;
	readonly textWidth?: string;
	readonly tableRows?: number;
	readonly listItems?: number;
	readonly paragraphLines?: number;
	readonly style?: CSSProperties;
	readonly className?: string;
}

const animStyle: Record<SkeletonAnimation, CSSProperties> = {
	pulse: { animation: 'quenetiq-pulse 1.8s cubic-bezier(0.4,0,0.6,1) infinite' },
	wave: { animation: 'quenetiq-wave 1.6s ease-in-out infinite', background: 'linear-gradient(90deg, var(--quenetiq-skeleton-bg,#e2e8f0) 25%, var(--quenetiq-skeleton-shine,#f1f5f9) 50%, var(--quenetiq-skeleton-bg,#e2e8f0) 75%)', backgroundSize: '200% 100%' },
	none: {},
};

const baseLine = (w = '100%'): CSSProperties => ({
	height: 14, borderRadius: 4, width: w, background: 'var(--quenetiq-skeleton-bg, #e2e8f0)',
});

function SkeletonLine({ w, anim }: { readonly w?: string; readonly anim: SkeletonAnimation }) {
	return <div style={{ ...baseLine(w), ...animStyle[anim] }} />;
}

function SkeletonCard({ anim }: { readonly anim: SkeletonAnimation }) {
	return (
		<div style={{ border: '1px solid var(--quenetiq-skeleton-border, #e2e8f0)', borderRadius: 8, overflow: 'hidden' }}>
			<div style={{ width: '100%', height: 160, background: 'var(--quenetiq-skeleton-bg, #e2e8f0)', ...animStyle[anim] }} />
			<div style={{ padding: 16, display: 'flex', flexDirection: 'column', gap: 10 }}>
				<SkeletonLine w="70%" anim={anim} />
				<SkeletonLine anim={anim} />
				<SkeletonLine w="50%" anim={anim} />
			</div>
		</div>
	);
}

function SkeletonTable({ rows, anim }: { readonly rows: number; readonly anim: SkeletonAnimation }) {
	return (
		<div style={{ width: '100%' }}>
			{Array.from({ length: rows }, (_, i) => (
				<div key={i} style={{ display: 'flex', gap: 12, padding: '12px 0', borderBottom: '1px solid var(--quenetiq-skeleton-border, #e2e8f0)' }}>
					<div style={{ flex: 1, height: 16, borderRadius: 4, background: 'var(--quenetiq-skeleton-bg, #e2e8f0)', ...animStyle[anim] }} />
					<div style={{ flex: 1, height: 16, borderRadius: 4, background: 'var(--quenetiq-skeleton-bg, #e2e8f0)', ...animStyle[anim] }} />
					<div style={{ flex: 0.5, height: 16, borderRadius: 4, background: 'var(--quenetiq-skeleton-bg, #e2e8f0)', ...animStyle[anim] }} />
				</div>
			))}
		</div>
	);
}

function SkeletonList({ items, anim }: { readonly items: number; readonly anim: SkeletonAnimation }) {
	return (
		<div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
			{Array.from({ length: items }, (_, i) => (
				<div key={i} style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
					<div style={{ width: 32, height: 32, borderRadius: '50%', background: 'var(--quenetiq-skeleton-bg, #e2e8f0)', ...animStyle[anim] }} />
					<div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 8 }}>
						<SkeletonLine w="70%" anim={anim} />
						<SkeletonLine w="50%" anim={anim} />
					</div>
				</div>
			))}
		</div>
	);
}

function SkeletonParagraph({ lines, anim }: { readonly lines: number; readonly anim: SkeletonAnimation }) {
	return (
		<div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
			{Array.from({ length: lines }, (_, i) => (
				<SkeletonLine key={i} w={i === lines - 1 ? '60%' : '100%'} anim={anim} />
			))}
		</div>
	);
}

export function Skeleton({
	variant = 'text', animation = 'pulse', width, height, textWidth = '100%',
	tableRows = 5, listItems = 4, paragraphLines = 4, style, className = '',
}: SkeletonProps): ReactNode {
	const wrap: CSSProperties = { borderRadius: 4, overflow: 'hidden', width: width as string | undefined, height: height as string | undefined, ...style };

	const content = (() => {
		switch (variant) {
		case 'text': return <SkeletonLine w={textWidth} anim={animation} />;
		case 'circle': return <div style={{ width: 48, height: 48, borderRadius: '50%', background: 'var(--quenetiq-skeleton-bg, #e2e8f0)', ...animStyle[animation] }} />;
		case 'rect': return <div style={{ width: '100%', height: 120, borderRadius: 4, background: 'var(--quenetiq-skeleton-bg, #e2e8f0)', ...animStyle[animation] }} />;
		case 'card': return <SkeletonCard anim={animation} />;
		case 'table': return <SkeletonTable rows={tableRows} anim={animation} />;
		case 'list': return <SkeletonList items={listItems} anim={animation} />;
		case 'paragraph': return <SkeletonParagraph lines={paragraphLines} anim={animation} />;
		}
	})();

	return (
		<div className={`quenetiq-skeleton ${className}`.trim()} style={wrap} role="status" aria-label="Loading content">
			{content}
			<style>{`
				@keyframes quenetiq-pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.5; } }
				@keyframes quenetiq-wave { 0% { background-position: 200% 0; } 100% { background-position: -200% 0; } }
			`}</style>
		</div>
	);
}

// projects/quenetiq/vue/src/lib/skeleton.vue
<script setup lang="ts">
const props = withDefaults(defineProps<{
	variant?: 'text' | 'circle' | 'rect' | 'card' | 'table' | 'list' | 'paragraph';
	animation?: 'pulse' | 'wave' | 'none';
	width?: string;
	height?: string;
	textWidth?: string;
	tableRows?: number;
	listItems?: number;
	paragraphLines?: number;
}>(), {
	variant: 'text',
	animation: 'pulse',
	textWidth: '100%',
	tableRows: 5,
	listItems: 4,
	paragraphLines: 4,
});
</script>

<template>
	<div
		:class="['dumbql-skeleton', `dumbql-skeleton--${variant}`, `dumbql-skeleton--${animation}`]"
		:style="{ width, height }"
		role="status"
		aria-label="Loading content"
	>
		<template v-if="variant === 'text'">
			<div class="dumbql-skeleton__line" :style="{ width: textWidth }"></div>
		</template>
		<template v-else-if="variant === 'circle'">
			<div class="dumbql-skeleton__circle"></div>
		</template>
		<template v-else-if="variant === 'rect'">
			<div class="dumbql-skeleton__rect"></div>
		</template>
		<template v-else-if="variant === 'card'">
			<div class="dumbql-skeleton__card">
				<div class="dumbql-skeleton__card-img"></div>
				<div class="dumbql-skeleton__card-body">
					<div class="dumbql-skeleton__line dumbql-skeleton__line--title"></div>
					<div class="dumbql-skeleton__line"></div>
					<div class="dumbql-skeleton__line dumbql-skeleton__line--short"></div>
				</div>
			</div>
		</template>
		<template v-else-if="variant === 'table'">
			<div class="dumbql-skeleton__table">
				<div v-for="n in tableRows" :key="n" class="dumbql-skeleton__table-row">
					<div class="dumbql-skeleton__table-cell"></div>
					<div class="dumbql-skeleton__table-cell"></div>
					<div class="dumbql-skeleton__table-cell"></div>
				</div>
			</div>
		</template>
		<template v-else-if="variant === 'list'">
			<div class="dumbql-skeleton__list">
				<div v-for="n in listItems" :key="n" class="dumbql-skeleton__list-item">
					<div class="dumbql-skeleton__circle dumbql-skeleton__circle--sm"></div>
					<div class="dumbql-skeleton__list-text">
						<div class="dumbql-skeleton__line dumbql-skeleton__line--title"></div>
						<div class="dumbql-skeleton__line dumbql-skeleton__line--short"></div>
					</div>
				</div>
			</div>
		</template>
		<template v-else-if="variant === 'paragraph'">
			<div class="dumbql-skeleton__paragraph">
				<div
					v-for="n in paragraphLines"
					:key="n"
					class="dumbql-skeleton__line"
					:style="{ width: n === paragraphLines ? '60%' : '100%' }"
				></div>
			</div>
		</template>
	</div>
</template>

<style scoped>
.dumbql-skeleton { border-radius: 4px; overflow: hidden; }
.dumbql-skeleton__line { height: 14px; border-radius: 4px; width: 100%; background: var(--dumbql-skeleton-bg, #e2e8f0); }
.dumbql-skeleton__line--title { width: 70%; height: 18px; }
.dumbql-skeleton__line--short { width: 50%; }
.dumbql-skeleton__circle { width: 48px; height: 48px; border-radius: 50%; background: var(--dumbql-skeleton-bg, #e2e8f0); }
.dumbql-skeleton__circle--sm { width: 32px; height: 32px; }
.dumbql-skeleton__rect { width: 100%; height: 120px; border-radius: 4px; background: var(--dumbql-skeleton-bg, #e2e8f0); }
.dumbql-skeleton__card { border: 1px solid var(--dumbql-skeleton-border, #e2e8f0); border-radius: 8px; overflow: hidden; }
.dumbql-skeleton__card-img { width: 100%; height: 160px; background: var(--dumbql-skeleton-bg, #e2e8f0); }
.dumbql-skeleton__card-body { padding: 16px; display: flex; flex-direction: column; gap: 10px; }
.dumbql-skeleton__table { width: 100%; }
.dumbql-skeleton__table-row { display: flex; gap: 12px; padding: 12px 0; border-bottom: 1px solid var(--dumbql-skeleton-border, #e2e8f0); }
.dumbql-skeleton__table-cell { flex: 1; height: 16px; border-radius: 4px; background: var(--dumbql-skeleton-bg, #e2e8f0); }
.dumbql-skeleton__table-cell:last-child { flex: 0.5; }
.dumbql-skeleton__list { display: flex; flex-direction: column; gap: 16px; }
.dumbql-skeleton__list-item { display: flex; gap: 12px; align-items: center; }
.dumbql-skeleton__list-text { flex: 1; display: flex; flex-direction: column; gap: 8px; }
.dumbql-skeleton__paragraph { display: flex; flex-direction: column; gap: 10px; }

.dumbql-skeleton--pulse .dumbql-skeleton__line,
.dumbql-skeleton--pulse .dumbql-skeleton__circle,
.dumbql-skeleton--pulse .dumbql-skeleton__rect,
.dumbql-skeleton--pulse .dumbql-skeleton__card-img,
.dumbql-skeleton--pulse .dumbql-skeleton__table-cell { animation: dumbql-pulse 1.8s cubic-bezier(0.4, 0, 0.6, 1) infinite; }

.dumbql-skeleton--wave .dumbql-skeleton__line,
.dumbql-skeleton--wave .dumbql-skeleton__circle,
.dumbql-skeleton--wave .dumbql-skeleton__rect,
.dumbql-skeleton--wave .dumbql-skeleton__card-img,
.dumbql-skeleton--wave .dumbql-skeleton__table-cell { animation: dumbql-wave 1.6s ease-in-out infinite; background: linear-gradient(90deg, var(--dumbql-skeleton-bg, #e2e8f0) 25%, var(--dumbql-skeleton-shine, #f1f5f9) 50%, var(--dumbql-skeleton-bg, #e2e8f0) 75%); background-size: 200% 100%; }

@keyframes dumbql-pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.5; } }
@keyframes dumbql-wave { 0% { background-position: 200% 0; } 100% { background-position: -200% 0; } }
</style>
